// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cadastro_de_pessoas.Server.Data;

#nullable disable

namespace cadastro_de_pessoas.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018220931_NewDB")]
    partial class NewDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("cadastro_de_pessoas.Server.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PessoaCPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PessoaDataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PessoaDataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PessoaDataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("PessoaNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PessoaId");

                    b.HasIndex("PessoaCPF")
                        .IsUnique();

                    b.ToTable("Pessoas");
                });
#pragma warning restore 612, 618
        }
    }
}
